name: bank_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  google_fonts: ^4.0.5
  intl: ^0.18.1
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.0

flutter_native_splash:
  color: "#792AE2"
  image: assets/images/savings.png

  # android_12:
  #   image: assets/images/savings.png
  #   color: "#792AE2"
  #   icon_background_color: "#792AE2"
  #   image_dark: assets/images/savings.png
  #   color_dark: "#792AE2"
  #   icon_background_color_dark: "#792AE2"

  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
